### ISSUE TITLE
Stop the stream

### ISSUE THREAD

**Issue by eush77** [juliangruber/module-usage#1]
Sorry, I'm not very fluent with streams, but how would you stop it?

For example, if I need only first two examples and there are many, how can I stop the stream early? What method would you recommend?

**Comment by juliangruber** [comment]
lack of knowledge is nothing to be sorry for, not asking however is :)

try this: `stream.close()`

**Comment by eush77** [comment]
No, that's not working.

``` py
  usageStream.close();
              ^
TypeError: usageStream.close is not a function
```

[There is](https://github.com/nodejs/node/blob/6e3bccbc03ffbdf0420f4802b5d992bc27bc5b0f/lib/fs.js#L1857) however a `close` method on `fs.ReadStream`, but not on generic streams.

**Comment by juliangruber** [comment]
in the latest version i added `.destroy()` which should do the trick

**Comment by eush77** [comment]
So you have to explicitly propagate it throughout dependencies. That's sad…

Thanks!
